Repository vuejs/eslint-plugin-vue, pull requests merged in 2018-12, with the labels that each got.

#692 Chore: update vue-eslint-parser to v4
  lib/utils/indent-common.js
  package.json
  tests/fixtures/html-indent/v-filter-sequence-expression-01.vue
  tests/fixtures/html-indent/v-filter-sequence-expression-02.vue
  tests/fixtures/html-indent/v-filter-sequence-expression-03.vue
  tests/fixtures/html-indent/v-filter-sequence-expression-04.vue
  tests/fixtures/html-indent/v-filter-sequence-expression-05.vue
  tests/lib/rules/no-unused-vars.js
Labels: bug

#695 Changed the category of `html-quotes` to `strongly-recommended`.
  docs/rules/README.md
  docs/rules/html-quotes.md
  lib/configs/recommended.js
  lib/configs/strongly-recommended.js
  lib/rules/html-quotes.js
Labels: semver-major

#717 Chore: improve editor style in vuepress
  docs/.vuepress/components/eslint-code-block.vue
Labels: documents

#718 Fix: order in components for node 11
  lib/rules/order-in-components.js
Labels: bug, semver-patch

#723 docs: Add macOS key bind for opening preference
  docs/user-guide/README.md
Labels: documents

#706 Update "What is the latest version" Warning Link
  lib/rules/no-multi-spaces.js
  lib/utils/index.js
Labels: documents
