Repository vuejs/eslint-plugin-vue, pull requests merged in 2018-02, with the labels that each got.

#374 Fix: fix script-indent to prevent removing <script> tag (fixes #367)
  lib/utils/indent-common.js
  tests/fixtures/script-indent/no-linebreak-script.vue
Labels: bug, semver-patch

#380 [Update] Make `vue/max-attributes-per-line` fixable
  lib/rules/max-attributes-per-line.js
  tests/lib/rules/max-attributes-per-line.js
Labels: enhancement, semver-minor

#381 [Update] Make `vue/order-in-components` fixable
  lib/rules/order-in-components.js
  tests/lib/rules/order-in-components.js
Labels: enhancement, semver-minor

#392 Fix: no-async-in-computed-properties crash (fixes #390)
  lib/utils/index.js
  tests/lib/rules/no-async-in-computed-properties.js
Labels: bug, semver-patch

#394 Fix: valid-v-on false positive (fixes #351)
  lib/rules/valid-v-on.js
  tests/lib/rules/valid-v-on.js
Labels: bug, semver-patch

#395 Fix: indent rules false positive (fixes #375)
  lib/utils/indent-common.js
  tests/fixtures/html-indent/v-start-tag-02.vue
  tests/fixtures/html-indent/v-start-tag-03.vue
  tests/fixtures/html-indent/v-start-tag-04.vue
  tests/fixtures/html-indent/v-start-tag-05.vue
  tests/fixtures/script-indent/array-expression-02.vue
  tests/fixtures/script-indent/function-declaration-04.vue
  tests/fixtures/script-indent/object-expression-03.vue
Labels: bug, semver-patch

#404 Upgrade vue eslint parser
  lib/rules/prop-name-casing.js
  package.json
  tests/lib/rules/no-parsing-error.js
  tests/lib/rules/valid-v-show.js
Labels: semver-patch

#393 Docs: update README.md
  README.md
Labels: documents, semver-patch
