Repository vuejs/eslint-plugin-vue, pull requests merged in 2018-07, with the labels that each got.

#406 ⭐️New: Add `vue/no-use-v-if-with-v-for` rule
  README.md
  docs/rules/no-use-v-if-with-v-for.md
  lib/index.js
  lib/rules/no-use-v-if-with-v-for.js
  tests/lib/rules/no-use-v-if-with-v-for.js
Labels: semver-minor

#463 (Fixes #416) Allow "default" key to be used also as a Literal
  lib/rules/require-default-prop.js
  tests/lib/rules/require-default-prop.js
Labels: semver-patch

#464 (Fixes #420) Fix false positive in no-side-effect-in-cp
  lib/rules/no-side-effects-in-computed-properties.js
  lib/utils/index.js
  tests/lib/rules/no-side-effects-in-computed-properties.js
  tests/lib/utils/index.js
Labels: semver-patch

#465 (Fixes #436) Fix 'getComputedProperties'
  lib/utils/index.js
  tests/lib/rules/no-async-in-computed-properties.js
  tests/lib/utils/index.js
Labels: semver-patch

#513 Fix attribute-hyphenation ignore lists
  lib/rules/attribute-hyphenation.js
  tests/lib/rules/attribute-hyphenation.js
Labels: bug, semver-patch

#435 ⭐️New: Add `vue/no-v-html` rule
  docs/rules/no-v-html.md
  lib/rules/no-v-html.js
  tests/lib/rules/no-v-html.js
Labels: semver-minor

#524 ⚙️Chore: Add related links to rules docs (fixes #439)
  docs/rules/attributes-order.md
  docs/rules/html-self-closing.md
  docs/rules/max-attributes-per-line.md
  docs/rules/name-property-casing.md
  docs/rules/no-async-in-computed-properties.md
  docs/rules/no-confusing-v-for-v-if.md
  docs/rules/no-reserved-keys.md
  docs/rules/no-shared-component-data.md
  docs/rules/no-textarea-mustache.md
  docs/rules/no-use-v-if-with-v-for.md
  docs/rules/no-v-html.md
  docs/rules/order-in-components.md
  docs/rules/prop-name-casing.md
  docs/rules/require-component-is.md
  docs/rules/require-default-prop.md
  docs/rules/require-prop-types.md
  docs/rules/require-v-for-key.md
  docs/rules/require-valid-default-prop.md
  docs/rules/v-bind-style.md
  docs/rules/v-on-style.md
Labels: documents

#476 Fix: Allow props with `validator` without `type` in `vue/require-prop-types`
  docs/rules/require-prop-types.md
  lib/rules/require-prop-types.js
  tests/lib/rules/require-prop-types.js
Labels: enhancement, semver-patch

#421 🐛Fix: v-bind order in `vue/attribute-order` rule
  docs/rules/attributes-order.md
  lib/rules/attributes-order.js
  tests/lib/rules/attributes-order.js
Labels: semver-major

#528 📝Docs: Add "working-with-rules" section in README
  README.md
Labels: documents

#529 Ignore Boolean props in require-default-prop rule
  docs/rules/require-default-prop.md
  lib/rules/require-default-prop.js
  tests/lib/rules/require-default-prop.js
Labels: semver-patch

#397 ⭐️New: Add `vue/component-name-in-template-casing`
  README.md
  docs/rules/component-name-in-template-casing.md
  lib/configs/strongly-recommended.js
  lib/index.js
  lib/rules/component-name-in-template-casing.js
  tests/lib/rules/component-name-in-template-casing.js
Labels: semver-minor

#471 Add same order support on multiple types of attributes.
  docs/rules/attributes-order.md
  lib/rules/attributes-order.js
  tests/lib/rules/attributes-order.js
Labels: accepted proposition, enhancement

#158 ⭐️New: Add rule `no-template-shadow`.
  docs/rules/no-template-shadow.md
  lib/rules/no-template-shadow.js
  lib/utils/index.js
  tests/lib/rules/no-template-shadow.js
Labels: semver-minor
