Repository vuejs/eslint-plugin-vue, pull requests merged in 2018-09, with the labels that each got.

#579 Fix #519 add custom modifiers to `vue/valid-v-on`
  docs/rules/valid-v-on.md
  lib/rules/valid-v-on.js
  tests/lib/rules/valid-v-on.js
Labels: enhancement

#503 🐛Fix: incorrect indentation in `vue/script-indent` rule
  lib/utils/indent-common.js
  tests/fixtures/script-indent/array-expression-03.vue
  tests/fixtures/script-indent/array-expression-04.vue
  tests/fixtures/script-indent/indent-valid-fixture-01.vue
  tests/fixtures/script-indent/issue441.vue
  tests/fixtures/script-indent/issue443.vue
  tests/fixtures/script-indent/sequence-expression-04.vue
Labels: bug, semver-patch

#573 Adding default array example of correct rule
  docs/rules/require-valid-default-prop.md
Labels: documents
