Repository vuejs/eslint-plugin-vue, pull requests merged in 2019-02, with the labels that each got.

#481 ⭐️New: Add `vue/v-on-parens` rule
  docs/rules/README.md
  docs/rules/v-on-function-call.md
  lib/index.js
  lib/rules/v-on-function-call.js
  tests/lib/rules/v-on-function-call.js
Labels: semver-minor

#612 ⭐️New: Add rule `no-boolean-default`
  docs/rules/README.md
  docs/rules/no-boolean-default.md
  lib/index.js
  lib/rules/no-boolean-default.js
  tests/lib/rules/no-boolean-default.js
Labels: new rule proposition

#738 feat: ignore anchor tags in multiline rule
  docs/rules/multiline-html-element-content-newline.md
  docs/rules/singleline-html-element-content-newline.md
  lib/rules/multiline-html-element-content-newline.js
  lib/rules/singleline-html-element-content-newline.js
  lib/utils/inline-non-void-elements.json
  tests/lib/rules/multiline-html-element-content-newline.js
  tests/lib/rules/singleline-html-element-content-newline.js
Labels: accepted proposition

#816 Fix no async with empty returns
  lib/rules/no-async-in-computed-properties.js
  tests/lib/rules/no-async-in-computed-properties.js
Labels: bug

#807 Breaking: support new syntax in Vue.js 2.6
  docs/rules/attributes-order.md
  lib/rules/array-bracket-spacing.js
  lib/rules/attribute-hyphenation.js
  lib/rules/attributes-order.js
  lib/rules/block-spacing.js
  lib/rules/brace-style.js
  lib/rules/key-spacing.js
  lib/rules/max-attributes-per-line.js
  lib/rules/no-confusing-v-for-v-if.js
  lib/rules/no-duplicate-attributes.js
  lib/rules/no-unused-components.js
  lib/rules/no-use-v-if-with-v-for.js
  lib/rules/no-v-html.js
  lib/rules/object-curly-spacing.js
  lib/rules/require-v-for-key.js
  lib/rules/space-infix-ops.js
  lib/rules/space-unary-ops.js
  lib/rules/this-in-template.js
  lib/rules/use-v-on-exact.js
  lib/rules/v-bind-style.js
  lib/rules/v-on-function-call.js
  lib/rules/v-on-style.js
  lib/rules/valid-v-bind.js
  lib/rules/valid-v-cloak.js
  lib/rules/valid-v-else-if.js
  lib/rules/valid-v-else.js
  lib/rules/valid-v-for.js
  lib/rules/valid-v-html.js
  lib/rules/valid-v-if.js
  lib/rules/valid-v-model.js
  lib/rules/valid-v-on.js
  lib/rules/valid-v-once.js
  lib/rules/valid-v-pre.js
  lib/rules/valid-v-show.js
  lib/rules/valid-v-text.js
  lib/utils/indent-common.js
  lib/utils/index.js
  package.json
  tests/lib/rules/array-bracket-spacing.js
  tests/lib/rules/attribute-hyphenation.js
  tests/lib/rules/attributes-order.js
  tests/lib/rules/block-spacing.js
  tests/lib/rules/brace-style.js
  tests/lib/rules/comma-dangle.js
  tests/lib/rules/key-spacing.js
  tests/lib/rules/max-attributes-per-line.js
  tests/lib/rules/no-duplicate-attributes.js
  tests/lib/rules/no-multi-spaces.js
  tests/lib/rules/no-restricted-syntax.js
  tests/lib/rules/no-unused-vars.js
  tests/lib/rules/object-curly-spacing.js
  tests/lib/rules/space-infix-ops.js
  tests/lib/rules/space-unary-ops.js
  tests/lib/rules/this-in-template.js
  tests/lib/rules/use-v-on-exact.js
  tests/lib/rules/v-bind-style.js
Labels: enhancement, semver-major
