Repository vuejs/eslint-plugin-vue, pull requests merged in 2019-01, with the labels that each got.

#745 fix(no-async-in-computed-properties): Allow async in nested scopes
  lib/rules/no-async-in-computed-properties.js
  tests/lib/rules/no-async-in-computed-properties.js
Labels: enhancement

#714 Fix: Add `registeredComponentsOnly` option to `component-name-in-template-casing` rule
  docs/rules/component-name-in-template-casing.md
  lib/rules/component-name-in-template-casing.js
  lib/utils/regexp.js
  tests/lib/autofix.js
  tests/lib/rules/component-name-in-template-casing.js
  tests/lib/utils/regexp.js
Labels: enhancement, semver-minor

#581 ⭐️New: Add `vue/require-direct-export` rule
  docs/rules/README.md
  docs/rules/require-direct-export.md
  lib/index.js
  lib/rules/require-direct-export.js
  lib/utils/index.js
  tests/lib/rules/require-direct-export.js
Labels: accepted proposition, new rule proposition

#761 Chore: Update `http:` links to `https:`
  README.md
  docs/developer-guide/README.md
  docs/rules/jsx-uses-vars.md
  docs/user-guide/README.md
  lib/rules/require-default-prop.js
  package.json
  tests/lib/rules/require-default-prop.js
  tools/update-docs.js
Labels: documents

#760 Chore: Add link to Playground on documentation page
  docs/.vuepress/config.js
Labels: documents

#758 ⭐️New: Add `vue/no-restricted-syntax` rule
  docs/rules/README.md
  docs/rules/no-restricted-syntax.md
  lib/index.js
  lib/rules/no-restricted-syntax.js
  tests/lib/rules/no-restricted-syntax.js
Labels: new rule proposition

#759 Update: Add `allowEmptyLines` option to `vue/multiline-html-element-content-newline` rule
  docs/rules/multiline-html-element-content-newline.md
  lib/rules/multiline-html-element-content-newline.js
  tests/lib/rules/multiline-html-element-content-newline.js
Labels: enhancement
