Repository vuejs/eslint-plugin-vue, pull requests merged in 2020-05, with the labels that each got.

#1117 Add `vue/no-deprecated-html-element-is` rule
  docs/rules/README.md
  docs/rules/no-deprecated-html-element-is.md
  lib/configs/vue3-essential.js
  lib/index.js
  lib/rules/no-deprecated-html-element-is.js
  tests/lib/rules/no-deprecated-html-element-is.js
Labels: Vue.js 3.x, semver-major

#1118 Add `vue/no-deprecated-vue-config-keycodes` rule
  docs/rules/README.md
  docs/rules/no-deprecated-vue-config-keycodes.md
  lib/configs/vue3-essential.js
  lib/index.js
  lib/rules/no-deprecated-vue-config-keycodes.js
  tests/lib/rules/no-deprecated-html-element-is.js
  tests/lib/rules/no-deprecated-vue-config-keycodes.js
Labels: Vue.js 3.x, semver-major

#1119 Add `vue/no-deprecated-functional-template` rule
  docs/rules/README.md
  docs/rules/no-deprecated-functional-template.md
  lib/configs/vue3-essential.js
  lib/index.js
  lib/rules/no-deprecated-functional-template.js
  tests/lib/rules/no-deprecated-functional-template.js
Labels: Vue.js 3.x, semver-major

#1105 Rename `require-v-if-inside-transition` rule to `require-toggle-inside-transition`
  docs/rules/README.md
  docs/rules/require-toggle-inside-transition.md
  lib/configs/vue3-essential.js
  lib/index.js
  lib/rules/require-toggle-inside-transition.js
  tests/lib/rules/require-toggle-inside-transition.js
Labels: Vue.js 3.x, semver-major

#1124 Add `vue/require-explicit-emits` rule
  docs/rules/README.md
  docs/rules/no-deprecated-vue-config-keycodes.md
  docs/rules/require-explicit-emits.md
  lib/index.js
  lib/rules/no-async-in-computed-properties.js
  lib/rules/no-deprecated-events-api.js
  lib/rules/no-lifecycle-after-await.js
  lib/rules/no-setup-props-destructure.js
  lib/rules/no-side-effects-in-computed-properties.js
  lib/rules/no-watch-after-await.js
  lib/rules/require-explicit-emits.js
  lib/rules/require-render-return.js
  lib/rules/return-in-computed-property.js
  lib/utils/index.js
  tests/lib/rules/no-setup-props-destructure.js
  tests/lib/rules/require-explicit-emits.js
Labels: Vue.js 3.x, semver-major

#1125 Fixed wrong autofix in `vue/no-deprecated-v-on-number-modifiers` rule
  lib/rules/no-deprecated-v-on-number-modifiers.js
  lib/utils/keycode-to-key.js
  lib/utils/keycode-to-key.json
  tests/lib/rules/no-deprecated-v-on-number-modifiers.js
Labels: Vue.js 3.x, bug

#1129 Add `vue/return-in-emits-validator` rule
  docs/rules/README.md
  docs/rules/return-in-emits-validator.md
  lib/configs/vue3-essential.js
  lib/index.js
  lib/rules/return-in-emits-validator.js
  tests/lib/rules/return-in-emits-validator.js
Labels: Vue.js 3.x, semver-major

#1120 Improve HTML comment directives.
  docs/.vuepress/config.js
  docs/.vuepress/shim/module.js
  docs/rules/comment-directive.md
  docs/rules/no-template-target-blank.md
  docs/user-guide/README.md
  lib/rules/comment-directive.js
  package.json
  tests/lib/rules/comment-directive.js
Labels: semver-major

#1130 Add `vue/no-deprecated-v-on-native-modifier` rule
  docs/rules/README.md
  docs/rules/no-deprecated-v-on-native-modifier.md
  lib/configs/vue3-essential.js
  lib/index.js
  lib/rules/no-deprecated-v-on-native-modifier.js
  tests/lib/rules/no-deprecated-v-on-native-modifier.js
Labels: Vue.js 3.x, semver-major

#1133 Add `vue/no-deprecated-dollar-listeners-api` rule
  docs/rules/README.md
  docs/rules/no-deprecated-dollar-listeners-api.md
  lib/configs/vue3-essential.js
  lib/index.js
  lib/rules/no-deprecated-dollar-listeners-api.js
  tests/lib/rules/no-deprecated-dollar-listeners-api.js
  tests/lib/rules/no-deprecated-events-api.js
Labels: Vue.js 3.x, semver-major

#755 ⭐️New: Add rules of HTML comment styles
  docs/rules/README.md
  docs/rules/html-comment-content-newline.md
  docs/rules/html-comment-content-spacing.md
  docs/rules/html-comment-indent.md
  lib/configs/no-layout-rules.js
  lib/index.js
  lib/rules/html-comment-content-newline.js
  lib/rules/html-comment-content-spacing.js
  lib/rules/html-comment-indent.js
  lib/utils/html-comments.js
  tests/fixtures/utils/html-comments/abrupt-closing-of-empty-comment/comment-tokens.json
  tests/fixtures/utils/html-comments/abrupt-closing-of-empty-comment/source.vue
  tests/fixtures/utils/html-comments/blank1/comment-tokens.json
  tests/fixtures/utils/html-comments/blank1/source.vue
  tests/fixtures/utils/html-comments/blank2/comment-tokens.json
  tests/fixtures/utils/html-comments/blank2/source.vue
  tests/fixtures/utils/html-comments/decoration-empty-value/comment-tokens.json
  tests/fixtures/utils/html-comments/decoration-empty-value/source.vue
  tests/fixtures/utils/html-comments/decoration1/comment-tokens.json
  tests/fixtures/utils/html-comments/decoration1/source.vue
  tests/fixtures/utils/html-comments/decoration2/comment-tokens.json
  tests/fixtures/utils/html-comments/decoration2/source.vue
  tests/fixtures/utils/html-comments/decoration3/comment-tokens.json
  tests/fixtures/utils/html-comments/decoration3/source.vue
  tests/fixtures/utils/html-comments/empty/comment-tokens.json
  tests/fixtures/utils/html-comments/empty/source.vue
  tests/fixtures/utils/html-comments/ie-conditional-comments1/comment-tokens.json
  tests/fixtures/utils/html-comments/ie-conditional-comments1/source.vue
  tests/fixtures/utils/html-comments/ie-conditional-comments2/comment-tokens.json
  tests/fixtures/utils/html-comments/ie-conditional-comments2/source.vue
  tests/fixtures/utils/html-comments/incorrectly-closed-comment/comment-tokens.json
  tests/fixtures/utils/html-comments/incorrectly-closed-comment/source.vue
  tests/fixtures/utils/html-comments/non-decoration/comment-tokens.json
  tests/fixtures/utils/html-comments/non-decoration/source.vue
  tests/fixtures/utils/html-comments/script-comment/comment-tokens.json
  tests/fixtures/utils/html-comments/script-comment/source.vue
  tests/fixtures/utils/html-comments/test1/comment-tokens.json
  tests/fixtures/utils/html-comments/test1/source.vue
  tests/fixtures/utils/html-comments/test2/comment-tokens.json
  tests/fixtures/utils/html-comments/test2/source.vue
  tests/fixtures/utils/html-comments/test3/comment-tokens.json
  tests/fixtures/utils/html-comments/test3/source.vue
  tests/fixtures/utils/html-comments/test4/comment-tokens.json
  tests/fixtures/utils/html-comments/test4/source.vue
  tests/lib/rules/html-comment-content-newline.js
  tests/lib/rules/html-comment-content-spacing.js
  tests/lib/rules/html-comment-indent.js
  tests/lib/utils/html-comments.js
Labels: new rule proposition

#1135 Add FAQ about conflicts with Prettier.
  docs/user-guide/README.md
Labels: documents

#1143 Changed `vue/no-deprecated-dollar-listeners-api` and `vue/no-deprecated-events-api` rules to track the `this` variable.
  lib/rules/no-deprecated-dollar-listeners-api.js
  lib/rules/no-deprecated-events-api.js
  lib/rules/require-explicit-emits.js
  lib/utils/index.js
  tests/lib/rules/no-deprecated-dollar-listeners-api.js
  tests/lib/rules/no-deprecated-events-api.js
Labels: Vue.js 3.x

#1139 Fix false positives for target instance is given, in `vue/no-lifecycle-after-await` rule.
  lib/rules/no-lifecycle-after-await.js
  tests/lib/rules/no-lifecycle-after-await.js
Labels: Vue.js 3.x, bug

#1138 Fix false positives for arrow function in `vue/return-in-emits-validator`rule
  lib/rules/return-in-emits-validator.js
  tests/lib/rules/return-in-emits-validator.js
Labels: Vue.js 3.x, bug

#1146 Fix false positives for member call and autofix error in `vue/v-on-function-call` rule.
  lib/rules/v-on-function-call.js
  tests/lib/rules/v-on-function-call.js
Labels: bug

#1152 Fix some casing issues
  lib/rules/attribute-hyphenation.js
  lib/rules/component-definition-name-casing.js
  lib/rules/component-name-in-template-casing.js
  lib/rules/name-property-casing.js
  lib/rules/no-unregistered-components.js
  lib/rules/no-unused-components.js
  lib/rules/prop-name-casing.js
  lib/utils/casing.js
  tests/lib/rules/component-definition-name-casing.js
  tests/lib/rules/component-name-in-template-casing.js
  tests/lib/rules/name-property-casing.js
  tests/lib/rules/prop-name-casing.js
  tests/lib/utils/casing.js
Labels: bug

#1155 Add new `vue/no-arrow-functions-in-watch` rule
  docs/rules/README.md
  docs/rules/no-arrow-functions-in-watch.md
  lib/index.js
  lib/rules/no-arrow-functions-in-watch.js
  tests/lib/rules/no-arrow-functions-in-watch.js
Labels: new rule proposition

#1163 Fixed false negatives when using ignorePattern for `vue/no-unused-var` rule.
  lib/rules/no-unused-vars.js
  tests/lib/rules/no-unused-vars.js
Labels: bug

#1164 Fixed false negatives when `v-for` and `v-slot` mixed or use destructuring for `vue/no-unused-var` rule.
  lib/rules/no-unused-vars.js
  tests/lib/rules/no-unused-vars.js
Labels: bug

#1166 Add `vue/custom-event-name-casing` rule
  docs/rules/README.md
  docs/rules/custom-event-name-casing.md
  lib/configs/essential.js
  lib/configs/vue3-essential.js
  lib/index.js
  lib/rules/custom-event-name-casing.js
  tests/lib/rules/custom-event-name-casing.js
Labels: new rule proposition, semver-major

#1169 Fixed false positives for watch with properties in `vue/no-unused-properties` rule.
  lib/rules/no-unused-properties.js
  tests/lib/rules/no-unused-properties.js
Labels: bug

#1170 Fixed an error for v-slot in `vue/comma-style` rule.
  lib/rules/comma-style.js
  tests/lib/rules/comma-style.js
Labels: bug
