Repository vuejs/eslint-plugin-vue, pull requests merged in 2020-10, with the labels that each got.

#1305 Make rule vue/no-unregistered-components ignore recursive components
  lib/rules/no-unregistered-components.js
  tests/lib/rules/no-unregistered-components.js
Labels: bug

#1321 added options for events that ignore custom-event-name-casing
  docs/rules/custom-event-name-casing.md
  lib/rules/custom-event-name-casing.js
  tests/lib/rules/custom-event-name-casing.js
Labels: semver-minor

#1332 Upgrade vue-eslint-parser to 7.1.1 and fixed CRLF issues.
  README.md
  docs/developer-guide/README.md
  docs/rules/html-indent.md
  docs/rules/no-restricted-syntax.md
  docs/rules/script-indent.md
  package.json
  tests/lib/rules/v-on-function-call.js
  typings/eslint-plugin-vue/util-types/ast/v-ast.ts
Labels: bug

#1322 Change not to use ESLint internal modules
  docs/.vuepress/components/eslint-code-block.vue
  docs/.vuepress/config.js
  docs/.vuepress/shim/eslint/index.js
  docs/.vuepress/shim/eslint/lib/rules/index.js
  docs/rules/no-textarea-mustache.md
  docs/rules/no-unused-vars.md
  lib/rules/array-bracket-spacing.js
  lib/rules/arrow-spacing.js
  lib/rules/block-spacing.js
  lib/rules/brace-style.js
  lib/rules/camelcase.js
  lib/rules/comma-dangle.js
  lib/rules/comma-spacing.js
  lib/rules/comma-style.js
  lib/rules/dot-location.js
  lib/rules/dot-notation.js
  lib/rules/eqeqeq.js
  lib/rules/func-call-spacing.js
  lib/rules/key-spacing.js
  lib/rules/keyword-spacing.js
  lib/rules/no-empty-pattern.js
  lib/rules/no-extra-parens.js
  lib/rules/no-restricted-syntax.js
  lib/rules/no-sparse-arrays.js
  lib/rules/no-useless-concat.js
  lib/rules/object-curly-newline.js
  lib/rules/object-curly-spacing.js
  lib/rules/object-property-newline.js
  lib/rules/operator-linebreak.js
  lib/rules/prefer-template.js
  lib/rules/space-in-parens.js
  lib/rules/space-infix-ops.js
  lib/rules/space-unary-ops.js
  lib/rules/template-curly-spacing.js
  lib/utils/index.js
  package.json
  tools/setup-eslint-rule-types.js
  typings/eslint/index.d.ts
Labels: semver-minor

#1324 Fixed false positives when used via argument in `vue/no-unused-properties`
  lib/rules/no-unused-properties.js
  tests/lib/rules/no-unused-properties.js
Labels: bug

#1328 Add vue/block-tag-newline rule
  docs/rules/README.md
  docs/rules/block-tag-newline.md
  lib/configs/no-layout-rules.js
  lib/index.js
  lib/rules/block-tag-newline.js
  tests/lib/rules/block-tag-newline.js
Labels: new rule proposition

#1326 Add `vue/array-bracket-newline` rule
  docs/rules/README.md
  docs/rules/array-bracket-newline.md
  lib/configs/no-layout-rules.js
  lib/index.js
  lib/rules/array-bracket-newline.js
  tests/lib/rules/array-bracket-newline.js
Labels: new rule proposition
