Repository vuejs/eslint-plugin-vue, pull requests merged in 2020-07, with the labels that each got.

#1232 Fixed crash when using `vue/no-empty-component-block` and `vue/padding-line-between-blocks` rules in `.js` file
  lib/rules/no-empty-component-block.js
  lib/rules/padding-line-between-blocks.js
  tests/lib/rules-without-vue-sfc.js
  tests/lib/rules/no-empty-component-block.js
  tests/lib/rules/padding-line-between-blocks.js
  typings/eslint-plugin-vue/util-types/parser-services.ts
Labels: bug

#1236 Move `@types/semver` from dependencies to devDependencies.
  package.json
Labels: bug

#1237 Remove jsx:true from shareable configs.
  docs/user-guide/README.md
  lib/configs/base.js
  tools/update-lib-configs.js
Labels: semver-major

#1238 Add `vue/no-lone-template` rule
  docs/rules/README.md
  docs/rules/no-lone-template.md
  lib/configs/recommended.js
  lib/configs/vue3-recommended.js
  lib/index.js
  lib/rules/no-lone-template.js
  tests/lib/rules/no-lone-template.js
Labels: new rule proposition

#1239 Add `vue/no-dupe-v-else-if` rule
  docs/rules/README.md
  docs/rules/no-dupe-v-else-if.md
  lib/configs/essential.js
  lib/configs/vue3-essential.js
  lib/index.js
  lib/rules/no-dupe-v-else-if.js
  lib/utils/index.js
  tests/lib/rules/no-dupe-v-else-if.js
  typings/eslint-plugin-vue/util-types/ast/ast.ts
Labels: new rule proposition

#1242 Fixed `vue/no-unused-properties`, `vue/require-valid-default-prop`, `vue/require-default-prop` and `vue/no-multiple-objects-in-class` rules crash on sparse arrays.
  lib/rules/no-multiple-objects-in-class.js
  lib/rules/require-default-prop.js
  lib/rules/require-prop-type-constructor.js
  lib/rules/require-valid-default-prop.js
  lib/utils/index.js
  tests/lib/rules/no-multiple-objects-in-class.js
  tests/lib/rules/no-unused-properties.js
  tests/lib/rules/require-default-prop.js
  tests/lib/rules/require-valid-default-prop.js
  typings/eslint-plugin-vue/util-types/ast/es-ast.ts
Labels: bug

#1243 Add `vue/no-sparse-arrays` rule
  docs/rules/README.md
  docs/rules/no-sparse-arrays.md
  lib/index.js
  lib/rules/no-sparse-arrays.js
  tests/lib/rules/no-sparse-arrays.js
Labels: new rule proposition

#1251 Change category of `vue/require-explicit-emits` rule to `vue3-strongly-recommended`
  docs/rules/README.md
  docs/rules/require-explicit-emits.md
  lib/configs/vue3-strongly-recommended.js
  lib/rules/require-explicit-emits.js
Labels: Vue.js 3.x

#1254 Change the rules to support "v-is".
  docs/rules/attributes-order.md
  docs/rules/no-unsupported-features.md
  lib/rules/attributes-order.js
  lib/rules/no-unregistered-components.js
  lib/rules/no-unsupported-features.js
  lib/rules/no-unused-components.js
  lib/rules/syntaxes/v-is.js
  lib/utils/index.js
  tests/lib/rules/attributes-order.js
  tests/lib/rules/no-unregistered-components.js
  tests/lib/rules/no-unsupported-features/v-is.js
  tests/lib/rules/no-unused-components.js
Labels: Vue.js 3.x

#1255 Fix false positives for watch handler methods in `vue/no-unused-properties` rule
  lib/rules/no-unused-properties.js
  lib/utils/index.js
  tests/lib/rules/no-unused-properties.js
Labels: bug

#1258 Fix false negatives of "slot-scope" when "^3.0.0" is set in `vue/no-unsupported-features` rule.
  lib/rules/no-unsupported-features.js
  lib/rules/syntaxes/dynamic-directive-arguments.js
  lib/rules/syntaxes/scope-attribute.js
  lib/rules/syntaxes/slot-attribute.js
  lib/rules/syntaxes/slot-scope-attribute.js
  lib/rules/syntaxes/v-bind-prop-modifier-shorthand.js
  lib/rules/syntaxes/v-is.js
  lib/rules/syntaxes/v-model-argument.js
  lib/rules/syntaxes/v-model-custom-modifiers.js
  lib/rules/syntaxes/v-slot.js
  tests/lib/rules/no-unsupported-features/dynamic-directive-arguments.js
  tests/lib/rules/no-unsupported-features/slot-scope-attribute.js
  tests/lib/rules/no-unsupported-features/v-slot.js
Labels: bug

#1259 Add `allowProps` option to `vue/require-explicit-emits` rule.
  docs/rules/require-explicit-emits.md
  lib/rules/no-reserved-component-names.js
  lib/rules/require-explicit-emits.js
  lib/rules/require-valid-default-prop.js
  lib/utils/casing.js
  tests/lib/rules/require-explicit-emits.js
Labels: Vue.js 3.x

#1262 Fix reporting "Use the latest vue-eslint-parser" message in non-vue files.
  lib/rules/no-multi-spaces.js
  lib/utils/index.js
  tests/lib/rules-without-vue-eslint-parser.js
Labels: bug

#1267 Add `v-for-delimiter-style` rule
  docs/rules/README.md
  docs/rules/v-for-delimiter-style.md
  lib/configs/no-layout-rules.js
  lib/index.js
  lib/rules/v-for-delimiter-style.js
  tests/lib/rules/v-for-delimiter-style.js
Labels: new rule proposition
