Repository vuejs/eslint-plugin-vue, pull requests merged in 2022-05, with the labels that each got.

#1880 Check symbols before GOOD/BAD comments in docs
  docs/rules/no-restricted-class.md
  docs/rules/no-restricted-custom-event.md
  docs/rules/no-use-computed-property-like-method.md
  tools/update-docs.js
Labels: documentation

#1883 Enable `vue/html-closing-bracket-*` for top-level tags
  lib/rules/block-tag-newline.js
  lib/rules/html-closing-bracket-newline.js
  lib/rules/html-closing-bracket-spacing.js
  tests/lib/rules/html-closing-bracket-newline.js
  tests/lib/rules/html-closing-bracket-spacing.js
Labels: semver-major

#1846 Change default casing of `vue/custom-event-name-casing` rule to camelCase
  docs/rules/custom-event-name-casing.md
  lib/rules/custom-event-name-casing.js
  tests/lib/rules/custom-event-name-casing.js
Labels: semver-major

#1847 Drop support for Node.js v12
  .circleci/config.yml
  .eslintrc.js
  docs/.vuepress/components/eslint-code-block.vue
  docs/user-guide/README.md
  package.json
Labels: semver-major

#1849 Upgrade vue-eslint-parser
  docs/rules/README.md
  docs/rules/jsx-uses-vars.md
  docs/rules/script-setup-uses-vars.md
  docs/user-guide/README.md
  lib/configs/base.js
  lib/index.js
  lib/rules/script-setup-uses-vars.js
  package.json
  tests/lib/script-setup-vars.js
  tools/update-lib-index.js
Labels: semver-major

#1881 Remove deprecated rules
  docs/rules/README.md
  docs/rules/experimental-script-setup-vars.md
  docs/rules/name-property-casing.md
  docs/rules/no-confusing-v-for-v-if.md
  docs/rules/no-unregistered-components.md
  lib/index.js
  lib/removed-rules.js
  lib/rules/experimental-script-setup-vars.js
  lib/rules/name-property-casing.js
  lib/rules/no-confusing-v-for-v-if.js
  lib/rules/no-unregistered-components.js
  tests/lib/rules/experimental-script-setup-vars.js
  tests/lib/rules/name-property-casing.js
  tests/lib/rules/no-confusing-v-for-v-if.js
  tests/lib/rules/no-unregistered-components.js
  tests/lib/script-setup.js
  tools/update-docs-rules-index.js
  tools/update-docs.js
Labels: semver-major

#1890 Bump devDependencies to their newest versions
  package.json
Labels: dependencies
