Repository vuejs/eslint-plugin-vue, pull requests merged in 2022-02, with the labels that each got.

#1790 Fix false positives due to conflicts with other rules in `vue/no-unused-properties` rule
  lib/rules/no-unused-properties.js
  tests/lib/rules/no-unused-properties.js
Labels: bug

#1803 Fix broken links in docs
  README.md
  docs/README.md
  docs/rules/attributes-order.md
  docs/rules/component-api-style.md
  docs/rules/component-definition-name-casing.md
  docs/rules/component-name-in-template-casing.md
  docs/rules/component-tags-order.md
  docs/rules/custom-event-name-casing.md
  docs/rules/first-attribute-linebreak.md
  docs/rules/html-quotes.md
  docs/rules/html-self-closing.md
  docs/rules/match-component-file-name.md
  docs/rules/max-attributes-per-line.md
  docs/rules/multi-word-component-names.md
  docs/rules/name-property-casing.md
  docs/rules/new-line-between-multi-line-property.md
  docs/rules/next-tick-style.md
  docs/rules/no-arrow-functions-in-watch.md
  docs/rules/no-child-content.md
  docs/rules/no-confusing-v-for-v-if.md
  docs/rules/no-deprecated-data-object-declaration.md
  docs/rules/no-deprecated-dollar-scopedslots-api.md
  docs/rules/no-deprecated-events-api.md
  docs/rules/no-deprecated-filter.md
  docs/rules/no-deprecated-functional-template.md
  docs/rules/no-deprecated-html-element-is.md
  docs/rules/no-deprecated-inline-template.md
  docs/rules/no-deprecated-props-default-this.md
  docs/rules/no-deprecated-scope-attribute.md
  docs/rules/no-deprecated-slot-attribute.md
  docs/rules/no-deprecated-slot-scope-attribute.md
  docs/rules/no-deprecated-v-bind-sync.md
  docs/rules/no-deprecated-v-is.md
  docs/rules/no-deprecated-v-on-number-modifiers.md
  docs/rules/no-deprecated-vue-config-keycodes.md
  docs/rules/no-mutating-props.md
  docs/rules/no-reserved-component-names.md
  docs/rules/no-shared-component-data.md
  docs/rules/no-unsupported-features.md
  docs/rules/no-use-v-if-with-v-for.md
  docs/rules/no-v-for-template-key-on-child.md
  docs/rules/no-v-for-template-key.md
  docs/rules/one-component-per-file.md
  docs/rules/order-in-components.md
  docs/rules/prop-name-casing.md
  docs/rules/require-default-prop.md
  docs/rules/require-prop-types.md
  docs/rules/require-v-for-key.md
  docs/rules/script-indent.md
  docs/rules/v-bind-style.md
  docs/rules/v-on-style.md
  docs/rules/v-slot-style.md
  docs/rules/valid-next-tick.md
  docs/rules/valid-v-bind-sync.md
  lib/rules/no-use-v-if-with-v-for.js
Labels: bug, documentation

#1807 Link to related rules in docs
  docs/rules/no-boolean-default.md
  docs/rules/prefer-true-attribute-shorthand.md
  docs/rules/require-default-prop.md
Labels: documentation
