Repository vuejs/eslint-plugin-vue, pull requests merged in 2022-01, with the labels that each got.

#1755 Fix crash on `<textarea>` without end tag in `vue/html-indent` rule
  lib/utils/indent-common.js
  tests/lib/rules/html-indent.js
Labels: bug

#1756 Fix false positive for unknown emits definition in `vue/require-explicit-emits` rule
  lib/rules/no-boolean-default.js
  lib/rules/no-deprecated-props-default-this.js
  lib/rules/no-mutating-props.js
  lib/rules/no-reserved-keys.js
  lib/rules/no-reserved-props.js
  lib/rules/no-restricted-props.js
  lib/rules/prop-name-casing.js
  lib/rules/require-default-prop.js
  lib/rules/require-emit-validator.js
  lib/rules/require-explicit-emits.js
  lib/rules/require-prop-type-constructor.js
  lib/rules/require-prop-types.js
  lib/rules/require-valid-default-prop.js
  lib/rules/return-in-emits-validator.js
  lib/utils/index.js
  tests/lib/rules/require-explicit-emits.js
  tests/lib/utils/index.js
  typings/eslint-plugin-vue/util-types/utils.ts
Labels: bug

#1762 Add `vue/object-shorthand` rule
  docs/rules/README.md
  docs/rules/object-shorthand.md
  lib/index.js
  lib/rules/object-shorthand.js
  tests/lib/rules/object-shorthand.js
Labels: new rule proposition

#1768 Improve documentation
  docs/rules/README.md
  docs/rules/array-bracket-newline.md
  docs/rules/array-bracket-spacing.md
  docs/rules/arrow-spacing.md
  docs/rules/block-spacing.md
  docs/rules/brace-style.md
  docs/rules/camelcase.md
  docs/rules/comma-dangle.md
  docs/rules/comma-spacing.md
  docs/rules/comma-style.md
  docs/rules/component-tags-order.md
  docs/rules/dot-location.md
  docs/rules/dot-notation.md
  docs/rules/eqeqeq.md
  docs/rules/func-call-spacing.md
  docs/rules/key-spacing.md
  docs/rules/keyword-spacing.md
  docs/rules/max-len.md
  docs/rules/no-constant-condition.md
  docs/rules/no-empty-pattern.md
  docs/rules/no-expose-after-await.md
  docs/rules/no-extra-parens.md
  docs/rules/no-irregular-whitespace.md
  docs/rules/no-loss-of-precision.md
  docs/rules/no-restricted-syntax.md
  docs/rules/no-sparse-arrays.md
  docs/rules/no-useless-concat.md
  docs/rules/object-curly-newline.md
  docs/rules/object-curly-spacing.md
  docs/rules/object-property-newline.md
  docs/rules/object-shorthand.md
  docs/rules/operator-linebreak.md
  docs/rules/prefer-template.md
  docs/rules/space-in-parens.md
  docs/rules/space-infix-ops.md
  docs/rules/space-unary-ops.md
  docs/rules/template-curly-spacing.md
  lib/rules/max-len.js
  lib/rules/no-irregular-whitespace.js
  lib/utils/index.js
Labels: documentation

#1769 Add `vue/quote-props` rule
  docs/rules/README.md
  docs/rules/quote-props.md
  lib/index.js
  lib/rules/quote-props.js
  lib/utils/index.js
  tests/lib/rules/quote-props.js
  typings/eslint-plugin-vue/util-types/parser-services.ts
  typings/eslint/index.d.ts
Labels: new rule proposition

#1770 Fix false positives for import brace in `vue/script-indent` rule
  lib/utils/indent-common.js
  tests/fixtures/script-indent/import-declaration-12.vue
Labels: bug

#1771 Fix false positives for `v-bind="obj"` with `v-model` in `vue/attributes-order` rule
  lib/rules/attributes-order.js
  tests/lib/rules/attributes-order.js
Labels: bug

#1775 Fix false positives for CSS `v-bind()` in `vue/no-extra-parens` rule
  lib/rules/no-extra-parens.js
  tests/lib/rules/no-extra-parens.js
Labels: bug

#1777 Skip conditional expressions in `vue/valid-next-tick`
  lib/rules/valid-next-tick.js
  tests/lib/rules/valid-next-tick.js
Labels: bug
