Repository vuejs/eslint-plugin-vue, pull requests merged in 2024-12, with the labels that each got.

#2153 Add `slots`+`expose` to `vue/order-in-components` default order
  docs/rules/order-in-components.md
  lib/rules/order-in-components.js
  tests/lib/rules/order-in-components.js
Labels: breaking change

#2171 Add update-resources script
  .github/workflows/check-for-resources-update.yml
  lib/utils/deprecated-html-elements.json
  lib/utils/html-elements.json
  lib/utils/svg-elements.json
  package.json
  tests/lib/rules/no-reserved-component-names.js
  tools/lib/http.js
  tools/update-html-resources.js
  tools/update-resources.js
  tools/update-vue3-export-names.js
  tools/update.js
Labels: breaking change

#2630 Change Versioning Policy
  README.md
  docs/index.md
Labels: semver-major, breaking change

#2642 fix typo in rule description
  docs/rules/html-comment-content-newline.md
  docs/rules/index.md
  lib/rules/html-comment-content-newline.js
Labels: documentation

#2641 Improve rules docs source readability
  docs/rules/index.md
  tools/update-docs-rules-index.js
Labels: documentation

#2645 Remove deprecated rules
  docs/rules/component-tags-order.md
  docs/rules/index.md
  docs/rules/no-invalid-model-keys.md
  docs/rules/no-ref-object-destructure.md
  docs/rules/no-setup-props-destructure.md
  docs/rules/script-setup-uses-vars.md
  docs/rules/v-on-function-call.md
  lib/index.js
  lib/removed-rules.js
  lib/rules/component-tags-order.js
  lib/rules/no-invalid-model-keys.js
  lib/rules/no-ref-object-destructure.js
  lib/rules/no-setup-props-destructure.js
  lib/rules/script-setup-uses-vars.js
  lib/rules/v-on-function-call.js
  tests/lib/rules/component-tags-order.js
  tests/lib/rules/no-invalid-model-keys.js
  tests/lib/rules/no-ref-object-destructure.js
  tests/lib/rules/no-setup-props-destructure.js
  tests/lib/rules/script-setup-uses-vars.js
  tests/lib/rules/v-on-function-call.js
Labels: semver-major, breaking change

#2646 Fix sidebar categories in rule docs
  docs/.vitepress/config.mts
Labels: documentation

#2652 Remove setup-compiler-macros environments
  lib/index.d.ts
  lib/index.js
  tools/update-lib-index.js
Labels: semver-major, breaking change

#2656 Update development dependencies
  eslint.config.js
  lib/rules/html-button-has-type.js
  lib/rules/no-irregular-whitespace.js
  lib/rules/require-macro-variable-name.js
  lib/rules/sort-keys.js
  package.json
Labels: meta
