Repository vuejs/eslint-plugin-vue, pull requests merged in 2025-01, with the labels that each got.

#2664 Move unused ESLint config for internal rules to main ESLint config
  eslint-internal-rules/.eslintrc.json
  eslint.config.js
Labels: meta

#2671 Update `vue/no-implicit-coercion` rule docs
  docs/rules/index.md
  docs/rules/no-implicit-coercion.md
Labels: documentation

#2669 Drop support for old versions of ESLint and Node.js
  .circleci/config.yml
  .github/workflows/CI.yml
  .github/workflows/check-for-resources-update.yml
  docs/user-guide/index.md
  lib/configs/base.js
  package.json
  tools/update-lib-configs.js
Labels: semver-major, breaking change
